bodega/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bodegaapp.urls')),
]

bodegaapp/urls.py
from django.urls import path
from .views import index, listPersona, listRecursoPersona, personaForm, recursoForm, listRecurso, personaFormEdit, recursoFormEdit

app_name = 'bodega'

urlpatterns = [
    path('', index, name = 'index'),
    path('listPersona',  listPersona, name = 'listPersona'),
    path('listRecurso',  listRecurso, name = 'listRecurso'),
    path('<int:persona_identificacion>/listRecursoPersona', listRecursoPersona, name = 'listRecursoPersona'),
    path('personaNueva', personaForm, name = 'personaNueva'),
    path('recursoNuevo', recursoForm, name = 'recursoNuevo'),
    path('<int:persona_id>/personaEdit', personaFormEdit, name = 'personaEdit'),
    path('<int:recurso_codigo>/recursoEdit', recursoFormEdit, name = 'recursoEdit'),
]

bodegaapp/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    identificacion = models.IntegerField(primary_key=True)
    nombres = models.CharField(max_length = 50)
    apellidos = models.CharField(max_length = 50)

    def __str__(self):
        return '%s %s' %(self.nombres, self.apellidos)

class Recurso(models.Model):
    categoria = models.CharField(max_length = 50)
    codigo = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length = 50)
    marca = models.CharField(max_length = 50)
    serie = models.CharField(max_length = 50)
    persona = models.ForeignKey(Persona, null = True, blank = True, on_delete = models.CASCADE)

    def __str__(self):
        return self.nombre

bodegaapp/forms.py
from django import forms
from .models import Persona, Recurso

class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = [
            'identificacion',
            'nombres',
            'apellidos',
        ]
        labels = {
            'identificacion' : 'Identificacion', 
            'nombres' : 'Nombres',
            'apellidos' : 'Apellidos',
        }
        widgets = {
            'identificacion' : forms.NumberInput(attrs={'class':'form-control'}), 
            'nombres' : forms.TextInput(attrs={'class':'form-control'}),
            'apellidos' : forms.TextInput(attrs={'class':'form-control'}),
        }

class RecursoForm(forms.ModelForm):
    class Meta:
        model = Recurso
        fields = [
            'categoria',
            'codigo',
            'nombre',
            'marca',
            'serie',
            'persona',
        ]
        labels = {
            'categoria' : 'Categoria',
            'codigo' : 'Codigo',
            'nombre' : 'Nombre',
            'marca' : 'Marca',
            'serie' : 'Serie',
            'persona' : 'Persona',
        }
        widgets = {
            'categoria' : forms.TextInput(attrs={'class':'form-control'}),
            'codigo' : forms.NumberInput(attrs={'class':'form-control'}),
            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'marca' : forms.TextInput(attrs={'class':'form-control'}),
            'serie' : forms.TextInput(attrs={'class':'form-control'}),
            'persona' : forms.Select(attrs={'class':'form-control'}),
        }

bodegaapp/views.py
from django.shortcuts import render, redirect
from .models import Persona, Recurso
from .forms import PersonaForm, RecursoForm
# Create your views here.

def index(request):
    return render(request, 'base/base.html')

def listPersona(request):
    personas = Persona.objects.all()
    return render(request, 'bodega/listPersona.html', {'personas' : personas})

def listRecurso(request):
    recursos = Recurso.objects.all()
    return render(request, 'bodega/listRecurso.html', {'recursos' : recursos})

def listRecursoPersona(request, persona_identificacion):
    recursoPersona = Persona.objects.get(identificacion = persona_identificacion)
    return render(request, 'bodega/listRecursoPersona.html', {'recursoPersona' : recursoPersona})

def personaForm(request):
    if request.method == 'POST':
        form = PersonaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('bodega:listPersona')
    else:
        form = PersonaForm()
    return render(request, 'bodega/crearForm.html', {'form': form})

def recursoForm(request):
    if request.method == 'POST':
        form = RecursoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('bodega:listRecurso')
    else:
        form = RecursoForm()
    return render(request, 'bodega/crearForm.html', {'form': form})

def personaFormEdit(request, persona_id):
    persona = Persona.objects.get(pk = persona_id)
    if request.method == 'GET':
        form = PersonaForm(instance=persona)
    else:
        form = PersonaForm(request.POST, instance=persona)
        if form.is_valid():
            form.save()
        return redirect('bodega:listPersona')
    return render(request, 'bodega/crearForm.html', {'form': form})

def recursoFormEdit(request, recurso_codigo):
    recurso = Recurso.objects.get(codigo = recurso_codigo)
    if request.method == 'GET':
        form = RecursoForm(instance=recurso)
    else:
        form = RecursoForm(request.POST, instance=recurso)
        if form.is_valid():
            form.save()
        return redirect('bodega:listRecurso')
    return render(request, 'bodega/crearForm.html', {'form': form})

bodegaapp/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Document {% endblock %}</title>
</head>
<body>


{% block navbar %}
<nav class="navbar navbar-expand-lg bg-info text-uppercase" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger text-dark" href="{% url 'bodega:index' %}">Mi Bodega.</a>
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-info text-dark rounded collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
        </button>
        <div class="navbar-collapse collapse" id="navbarResponsive" style="">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-dark" href="{% url 'bodega:listPersona' %}">Personas</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger text-dark" href="{% url 'bodega:listRecurso' %}">Recursos</a>
            </li>
        </ul>
        </div>
    </div>
</nav>
{% endblock %}
    
<div class="container">
{% block header %}
    <h4></h4>
{% endblock %}
</div>    

<div class="container">
{% block content %}
    <h5></h5>
{% endblock %}
</div>

<div class="container">
{% block footer %}
    <h1 class="container text-center">Esta es una prueba de DJANGO.</h1>
{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

bodegaapp/templates/bodega/crearForm.html
{% extends 'base/base.html' %}


{% block header %}
    <h1>Ingrece los datos:</h1>
{% endblock header %}
    

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='Guardar.'>
    </form>
{% endblock %}


{% block footer %}
    
{% endblock footer %}
    

bodegaapp/templates/bodega/listPersona.html
{% extends 'base/base.html' %}


{% block header %}
    <h1>Lista de Personas:</h1>
{% endblock header %}
    

{% block content %}
    <a class="btn btn-info" href="{% url 'bodega:personaNueva' %}">Nueva Persona.</a>
{% endblock %}


{% block footer %}
<table class="table table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>Identificacion</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Recursos</th>
        </tr>
    </thead>

    <tbody>   
        {% if personas %}
            {% for persona in personas %}
            <tr>
                <td>{{ persona.identificacion }}</td>
                <td>{{ persona.nombres }}</td>
                <td>{{ persona.apellidos }}</td>
                <td><a href="{% url 'bodega:listRecursoPersona' persona.identificacion %}">Ver.</a></td>
            </tr>          
            {% endfor %}
        {% else %}
            <tr><td class="text-center" colspan="7">No se encontraron Registros de Persona.</td></tr>
        {% endif %}
    </tbody> 
</table> 
{% endblock footer %}
    

bodegaapp/templates/bodega/listRecurso.html
{% extends 'base/base.html' %}

{% block header %}
    <h1>Lista de Recursos:</h1>
{% endblock header %}
    

{% block content %}
<a class="btn btn-info" href="{% url 'bodega:recursoNuevo' %}">Nuevo Recurso.</a>
{% endblock %}


{% block footer %}
<table class="table table-borderless table-sm">
    <thead class="thead-light">
        <tr>
            <th>Categoria</th>
            <th>Código</th>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Serie</th>
            <th>Asignado a </th>
            <th>Asignar a otra Persona</th>
        </tr>
    </thead>

    <tbody>   
        {% if recursos %}
            {% for recurso in recursos %}
            <tr>
                <td>{{ recurso.categoria }}</td>
                <td>{{ recurso.codigo }}</td>
                <td>{{ recurso.nombre }}</td>
                <td>{{ recurso.marca }}</td>
                <td>{{ recurso.serie }}</td>
                <td>{{ recurso.persona }}</td>
                <td><a href="{% url 'bodega:recursoEdit' recurso.codigo %}">Ir.</a></td>
            </tr>          
            {% endfor %}
        {% else %}
            <tr><td class="text-center" colspan="7">No se encontraron Registros de Recurso.</td></tr>
        {% endif %}
    </tbody> 
</table>  
{% endblock footer %}

bodegaapp/templates/bodega/listRecursoPersona.html
{% extends 'base/base.html' %}

{% block header %}
    <h2>{{ recursoPersona }}</h2>
{% endblock %}

{% block content %}
    
{% endblock %}


{% block footer %}
<table class="table table-borderless table-sm">
        <thead class="thead-light">
            <tr>
                <th>Categoria</th>
                <th>Código</th>
                <th>Nombre</th>
                <th>Marca</th>
                <th>Serie</th>
                <th>Asignado a </th>
                <th>Asignar a otra Persona</th>
            </tr>
        </thead>
    
        <tbody>   
            {% if recursoPersona.recurso_set.all %}
                {% for recurso in recursoPersona.recurso_set.all %}
                <tr>
                    <td>{{ recurso.categoria }}</td>
                    <td>{{ recurso.codigo }}</td>
                    <td>{{ recurso.nombre }}</td>
                    <td>{{ recurso.marca }}</td>
                    <td>{{ recurso.serie }}</td>
                    <td>{{ recurso.persona }}</td>
                    <td><a href="{% url 'bodega:recursoEdit' recurso.codigo %}">Ir.</a></td>
                </tr>          
                {% endfor %}
            {% else %}
                <tr><td class="text-center" colspan="7">No se encontraron Registros de Recurso.</td></tr>
            {% endif %}
        </tbody> 
    </table>  
{% endblock footer %}
    